/*
 * Integration Adapter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"github.com/gin-gonic/gin"
)

type InventoriesAPI interface {


    // UpdateStockLevel Post /inventories/update
    // Update Stock Level 
     UpdateStockLevel(c *gin.Context)

}