/*
 * Integration Adapter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type UpdateStockLevel200ResponseError struct {

	Code string `json:"code,omitempty"`

	Message string `json:"message,omitempty"`
}
