/*
 * Integration Adapter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type UpdateStockLevelRequest struct {

	Id string `json:"id,omitempty"`

	Requests []UpdateStockLevelRequestRequestsInner `json:"requests,omitempty"`

	Store UpdateStockLevelRequestStore `json:"store,omitempty"`
}
