/*
 * Integration Adapter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type ProductsRequestProductsInner struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`
}
