/*
 * Integration Adapter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type UpdateStockLevelRequestRequestsInner struct {

	ChannelLocationCode string `json:"channel_location_code,omitempty"`

	ChannelLocationId string `json:"channel_location_id,omitempty"`

	ChannelProductId string `json:"channel_product_id,omitempty"`

	ChannelProductVariantId string `json:"channel_product_variant_id,omitempty"`

	ChannelProductVariantSku string `json:"channel_product_variant_sku,omitempty"`

	DeltaStock float32 `json:"delta_stock,omitempty"`

	ExactStock float32 `json:"exact_stock,omitempty"`

	LocationCode string `json:"location_code,omitempty"`

	LocationId string `json:"location_id,omitempty"`

	ProductId string `json:"product_id,omitempty"`

	ProductVariantId string `json:"product_variant_id,omitempty"`

	ProductVariantSku string `json:"product_variant_sku,omitempty"`
}
