/*
 * Integration Adapter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type SalesOrdersRequestSalesOrdersInner struct {

	ChannelId string `json:"channel_id,omitempty"`

	Date float32 `json:"date,omitempty"`

	Id string `json:"id,omitempty"`
}
