/*
 * Integration Adapter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type DeliveryOrdersRequest struct {

	Action string `json:"action,omitempty"`

	DeliveryOrders []DeliveryOrdersRequestDeliveryOrdersInner `json:"delivery_orders,omitempty"`

	Id string `json:"id,omitempty"`

	Object string `json:"object,omitempty"`
}
