/*
 * Integration Adapter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type AccountsRequestAccountsInner struct {

	Data string `json:"data,omitempty"`
}
