/*
Integration Adapter

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the SalesOrdersRequestSalesOrdersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SalesOrdersRequestSalesOrdersInner{}

// SalesOrdersRequestSalesOrdersInner struct for SalesOrdersRequestSalesOrdersInner
type SalesOrdersRequestSalesOrdersInner struct {
	ChannelId *string `json:"channel_id,omitempty"`
	Date *float32 `json:"date,omitempty"`
	Id *string `json:"id,omitempty"`
}

// NewSalesOrdersRequestSalesOrdersInner instantiates a new SalesOrdersRequestSalesOrdersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSalesOrdersRequestSalesOrdersInner() *SalesOrdersRequestSalesOrdersInner {
	this := SalesOrdersRequestSalesOrdersInner{}
	return &this
}

// NewSalesOrdersRequestSalesOrdersInnerWithDefaults instantiates a new SalesOrdersRequestSalesOrdersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSalesOrdersRequestSalesOrdersInnerWithDefaults() *SalesOrdersRequestSalesOrdersInner {
	this := SalesOrdersRequestSalesOrdersInner{}
	return &this
}

// GetChannelId returns the ChannelId field value if set, zero value otherwise.
func (o *SalesOrdersRequestSalesOrdersInner) GetChannelId() string {
	if o == nil || IsNil(o.ChannelId) {
		var ret string
		return ret
	}
	return *o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesOrdersRequestSalesOrdersInner) GetChannelIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChannelId) {
		return nil, false
	}
	return o.ChannelId, true
}

// HasChannelId returns a boolean if a field has been set.
func (o *SalesOrdersRequestSalesOrdersInner) HasChannelId() bool {
	if o != nil && !IsNil(o.ChannelId) {
		return true
	}

	return false
}

// SetChannelId gets a reference to the given string and assigns it to the ChannelId field.
func (o *SalesOrdersRequestSalesOrdersInner) SetChannelId(v string) {
	o.ChannelId = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *SalesOrdersRequestSalesOrdersInner) GetDate() float32 {
	if o == nil || IsNil(o.Date) {
		var ret float32
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesOrdersRequestSalesOrdersInner) GetDateOk() (*float32, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *SalesOrdersRequestSalesOrdersInner) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given float32 and assigns it to the Date field.
func (o *SalesOrdersRequestSalesOrdersInner) SetDate(v float32) {
	o.Date = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SalesOrdersRequestSalesOrdersInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesOrdersRequestSalesOrdersInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SalesOrdersRequestSalesOrdersInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SalesOrdersRequestSalesOrdersInner) SetId(v string) {
	o.Id = &v
}

func (o SalesOrdersRequestSalesOrdersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SalesOrdersRequestSalesOrdersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChannelId) {
		toSerialize["channel_id"] = o.ChannelId
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableSalesOrdersRequestSalesOrdersInner struct {
	value *SalesOrdersRequestSalesOrdersInner
	isSet bool
}

func (v NullableSalesOrdersRequestSalesOrdersInner) Get() *SalesOrdersRequestSalesOrdersInner {
	return v.value
}

func (v *NullableSalesOrdersRequestSalesOrdersInner) Set(val *SalesOrdersRequestSalesOrdersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSalesOrdersRequestSalesOrdersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSalesOrdersRequestSalesOrdersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSalesOrdersRequestSalesOrdersInner(val *SalesOrdersRequestSalesOrdersInner) *NullableSalesOrdersRequestSalesOrdersInner {
	return &NullableSalesOrdersRequestSalesOrdersInner{value: val, isSet: true}
}

func (v NullableSalesOrdersRequestSalesOrdersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSalesOrdersRequestSalesOrdersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


