/*
Integration Adapter

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the UpdateStockLevel400ResponseError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateStockLevel400ResponseError{}

// UpdateStockLevel400ResponseError struct for UpdateStockLevel400ResponseError
type UpdateStockLevel400ResponseError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewUpdateStockLevel400ResponseError instantiates a new UpdateStockLevel400ResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateStockLevel400ResponseError() *UpdateStockLevel400ResponseError {
	this := UpdateStockLevel400ResponseError{}
	return &this
}

// NewUpdateStockLevel400ResponseErrorWithDefaults instantiates a new UpdateStockLevel400ResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateStockLevel400ResponseErrorWithDefaults() *UpdateStockLevel400ResponseError {
	this := UpdateStockLevel400ResponseError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *UpdateStockLevel400ResponseError) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStockLevel400ResponseError) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *UpdateStockLevel400ResponseError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *UpdateStockLevel400ResponseError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UpdateStockLevel400ResponseError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStockLevel400ResponseError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UpdateStockLevel400ResponseError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UpdateStockLevel400ResponseError) SetMessage(v string) {
	o.Message = &v
}

func (o UpdateStockLevel400ResponseError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateStockLevel400ResponseError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableUpdateStockLevel400ResponseError struct {
	value *UpdateStockLevel400ResponseError
	isSet bool
}

func (v NullableUpdateStockLevel400ResponseError) Get() *UpdateStockLevel400ResponseError {
	return v.value
}

func (v *NullableUpdateStockLevel400ResponseError) Set(val *UpdateStockLevel400ResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateStockLevel400ResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateStockLevel400ResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateStockLevel400ResponseError(val *UpdateStockLevel400ResponseError) *NullableUpdateStockLevel400ResponseError {
	return &NullableUpdateStockLevel400ResponseError{value: val, isSet: true}
}

func (v NullableUpdateStockLevel400ResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateStockLevel400ResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


