/*
Integration Adapter

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the DeliveryOrdersRequestDeliveryOrdersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliveryOrdersRequestDeliveryOrdersInner{}

// DeliveryOrdersRequestDeliveryOrdersInner struct for DeliveryOrdersRequestDeliveryOrdersInner
type DeliveryOrdersRequestDeliveryOrdersInner struct {
	ChannelId *string `json:"channel_id,omitempty"`
	ChannelSalesOrderId *string `json:"channel_sales_order_id,omitempty"`
	Date *float32 `json:"date,omitempty"`
	Id *string `json:"id,omitempty"`
	SalesOrderId *string `json:"sales_order_id,omitempty"`
}

// NewDeliveryOrdersRequestDeliveryOrdersInner instantiates a new DeliveryOrdersRequestDeliveryOrdersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliveryOrdersRequestDeliveryOrdersInner() *DeliveryOrdersRequestDeliveryOrdersInner {
	this := DeliveryOrdersRequestDeliveryOrdersInner{}
	return &this
}

// NewDeliveryOrdersRequestDeliveryOrdersInnerWithDefaults instantiates a new DeliveryOrdersRequestDeliveryOrdersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryOrdersRequestDeliveryOrdersInnerWithDefaults() *DeliveryOrdersRequestDeliveryOrdersInner {
	this := DeliveryOrdersRequestDeliveryOrdersInner{}
	return &this
}

// GetChannelId returns the ChannelId field value if set, zero value otherwise.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) GetChannelId() string {
	if o == nil || IsNil(o.ChannelId) {
		var ret string
		return ret
	}
	return *o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) GetChannelIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChannelId) {
		return nil, false
	}
	return o.ChannelId, true
}

// HasChannelId returns a boolean if a field has been set.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) HasChannelId() bool {
	if o != nil && !IsNil(o.ChannelId) {
		return true
	}

	return false
}

// SetChannelId gets a reference to the given string and assigns it to the ChannelId field.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) SetChannelId(v string) {
	o.ChannelId = &v
}

// GetChannelSalesOrderId returns the ChannelSalesOrderId field value if set, zero value otherwise.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) GetChannelSalesOrderId() string {
	if o == nil || IsNil(o.ChannelSalesOrderId) {
		var ret string
		return ret
	}
	return *o.ChannelSalesOrderId
}

// GetChannelSalesOrderIdOk returns a tuple with the ChannelSalesOrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) GetChannelSalesOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChannelSalesOrderId) {
		return nil, false
	}
	return o.ChannelSalesOrderId, true
}

// HasChannelSalesOrderId returns a boolean if a field has been set.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) HasChannelSalesOrderId() bool {
	if o != nil && !IsNil(o.ChannelSalesOrderId) {
		return true
	}

	return false
}

// SetChannelSalesOrderId gets a reference to the given string and assigns it to the ChannelSalesOrderId field.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) SetChannelSalesOrderId(v string) {
	o.ChannelSalesOrderId = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) GetDate() float32 {
	if o == nil || IsNil(o.Date) {
		var ret float32
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) GetDateOk() (*float32, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given float32 and assigns it to the Date field.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) SetDate(v float32) {
	o.Date = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) SetId(v string) {
	o.Id = &v
}

// GetSalesOrderId returns the SalesOrderId field value if set, zero value otherwise.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) GetSalesOrderId() string {
	if o == nil || IsNil(o.SalesOrderId) {
		var ret string
		return ret
	}
	return *o.SalesOrderId
}

// GetSalesOrderIdOk returns a tuple with the SalesOrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) GetSalesOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.SalesOrderId) {
		return nil, false
	}
	return o.SalesOrderId, true
}

// HasSalesOrderId returns a boolean if a field has been set.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) HasSalesOrderId() bool {
	if o != nil && !IsNil(o.SalesOrderId) {
		return true
	}

	return false
}

// SetSalesOrderId gets a reference to the given string and assigns it to the SalesOrderId field.
func (o *DeliveryOrdersRequestDeliveryOrdersInner) SetSalesOrderId(v string) {
	o.SalesOrderId = &v
}

func (o DeliveryOrdersRequestDeliveryOrdersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliveryOrdersRequestDeliveryOrdersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChannelId) {
		toSerialize["channel_id"] = o.ChannelId
	}
	if !IsNil(o.ChannelSalesOrderId) {
		toSerialize["channel_sales_order_id"] = o.ChannelSalesOrderId
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.SalesOrderId) {
		toSerialize["sales_order_id"] = o.SalesOrderId
	}
	return toSerialize, nil
}

type NullableDeliveryOrdersRequestDeliveryOrdersInner struct {
	value *DeliveryOrdersRequestDeliveryOrdersInner
	isSet bool
}

func (v NullableDeliveryOrdersRequestDeliveryOrdersInner) Get() *DeliveryOrdersRequestDeliveryOrdersInner {
	return v.value
}

func (v *NullableDeliveryOrdersRequestDeliveryOrdersInner) Set(val *DeliveryOrdersRequestDeliveryOrdersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryOrdersRequestDeliveryOrdersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryOrdersRequestDeliveryOrdersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliveryOrdersRequestDeliveryOrdersInner(val *DeliveryOrdersRequestDeliveryOrdersInner) *NullableDeliveryOrdersRequestDeliveryOrdersInner {
	return &NullableDeliveryOrdersRequestDeliveryOrdersInner{value: val, isSet: true}
}

func (v NullableDeliveryOrdersRequestDeliveryOrdersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryOrdersRequestDeliveryOrdersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


