/*
Integration Adapter

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the DeliveryOrdersRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliveryOrdersRequest{}

// DeliveryOrdersRequest struct for DeliveryOrdersRequest
type DeliveryOrdersRequest struct {
	Action *string `json:"action,omitempty"`
	DeliveryOrders []DeliveryOrdersRequestDeliveryOrdersInner `json:"delivery_orders,omitempty"`
	Id *string `json:"id,omitempty"`
	Object *string `json:"object,omitempty"`
}

// NewDeliveryOrdersRequest instantiates a new DeliveryOrdersRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliveryOrdersRequest() *DeliveryOrdersRequest {
	this := DeliveryOrdersRequest{}
	return &this
}

// NewDeliveryOrdersRequestWithDefaults instantiates a new DeliveryOrdersRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryOrdersRequestWithDefaults() *DeliveryOrdersRequest {
	this := DeliveryOrdersRequest{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *DeliveryOrdersRequest) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryOrdersRequest) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *DeliveryOrdersRequest) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *DeliveryOrdersRequest) SetAction(v string) {
	o.Action = &v
}

// GetDeliveryOrders returns the DeliveryOrders field value if set, zero value otherwise.
func (o *DeliveryOrdersRequest) GetDeliveryOrders() []DeliveryOrdersRequestDeliveryOrdersInner {
	if o == nil || IsNil(o.DeliveryOrders) {
		var ret []DeliveryOrdersRequestDeliveryOrdersInner
		return ret
	}
	return o.DeliveryOrders
}

// GetDeliveryOrdersOk returns a tuple with the DeliveryOrders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryOrdersRequest) GetDeliveryOrdersOk() ([]DeliveryOrdersRequestDeliveryOrdersInner, bool) {
	if o == nil || IsNil(o.DeliveryOrders) {
		return nil, false
	}
	return o.DeliveryOrders, true
}

// HasDeliveryOrders returns a boolean if a field has been set.
func (o *DeliveryOrdersRequest) HasDeliveryOrders() bool {
	if o != nil && !IsNil(o.DeliveryOrders) {
		return true
	}

	return false
}

// SetDeliveryOrders gets a reference to the given []DeliveryOrdersRequestDeliveryOrdersInner and assigns it to the DeliveryOrders field.
func (o *DeliveryOrdersRequest) SetDeliveryOrders(v []DeliveryOrdersRequestDeliveryOrdersInner) {
	o.DeliveryOrders = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeliveryOrdersRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryOrdersRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeliveryOrdersRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DeliveryOrdersRequest) SetId(v string) {
	o.Id = &v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *DeliveryOrdersRequest) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryOrdersRequest) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *DeliveryOrdersRequest) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *DeliveryOrdersRequest) SetObject(v string) {
	o.Object = &v
}

func (o DeliveryOrdersRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliveryOrdersRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.DeliveryOrders) {
		toSerialize["delivery_orders"] = o.DeliveryOrders
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	return toSerialize, nil
}

type NullableDeliveryOrdersRequest struct {
	value *DeliveryOrdersRequest
	isSet bool
}

func (v NullableDeliveryOrdersRequest) Get() *DeliveryOrdersRequest {
	return v.value
}

func (v *NullableDeliveryOrdersRequest) Set(val *DeliveryOrdersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryOrdersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryOrdersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliveryOrdersRequest(val *DeliveryOrdersRequest) *NullableDeliveryOrdersRequest {
	return &NullableDeliveryOrdersRequest{value: val, isSet: true}
}

func (v NullableDeliveryOrdersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryOrdersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


