/*
Integration Adapter

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ProductsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductsRequest{}

// ProductsRequest struct for ProductsRequest
type ProductsRequest struct {
	Action *string `json:"action,omitempty"`
	Id *string `json:"id,omitempty"`
	Object *string `json:"object,omitempty"`
	Products []ProductsRequestProductsInner `json:"products,omitempty"`
}

// NewProductsRequest instantiates a new ProductsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductsRequest() *ProductsRequest {
	this := ProductsRequest{}
	return &this
}

// NewProductsRequestWithDefaults instantiates a new ProductsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductsRequestWithDefaults() *ProductsRequest {
	this := ProductsRequest{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *ProductsRequest) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductsRequest) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *ProductsRequest) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *ProductsRequest) SetAction(v string) {
	o.Action = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProductsRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductsRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProductsRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProductsRequest) SetId(v string) {
	o.Id = &v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *ProductsRequest) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductsRequest) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *ProductsRequest) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *ProductsRequest) SetObject(v string) {
	o.Object = &v
}

// GetProducts returns the Products field value if set, zero value otherwise.
func (o *ProductsRequest) GetProducts() []ProductsRequestProductsInner {
	if o == nil || IsNil(o.Products) {
		var ret []ProductsRequestProductsInner
		return ret
	}
	return o.Products
}

// GetProductsOk returns a tuple with the Products field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductsRequest) GetProductsOk() ([]ProductsRequestProductsInner, bool) {
	if o == nil || IsNil(o.Products) {
		return nil, false
	}
	return o.Products, true
}

// HasProducts returns a boolean if a field has been set.
func (o *ProductsRequest) HasProducts() bool {
	if o != nil && !IsNil(o.Products) {
		return true
	}

	return false
}

// SetProducts gets a reference to the given []ProductsRequestProductsInner and assigns it to the Products field.
func (o *ProductsRequest) SetProducts(v []ProductsRequestProductsInner) {
	o.Products = v
}

func (o ProductsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.Products) {
		toSerialize["products"] = o.Products
	}
	return toSerialize, nil
}

type NullableProductsRequest struct {
	value *ProductsRequest
	isSet bool
}

func (v NullableProductsRequest) Get() *ProductsRequest {
	return v.value
}

func (v *NullableProductsRequest) Set(val *ProductsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductsRequest(val *ProductsRequest) *NullableProductsRequest {
	return &NullableProductsRequest{value: val, isSet: true}
}

func (v NullableProductsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


