/*
Integration Adapter

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the UpdateStockLevel429ResponseError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateStockLevel429ResponseError{}

// UpdateStockLevel429ResponseError struct for UpdateStockLevel429ResponseError
type UpdateStockLevel429ResponseError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewUpdateStockLevel429ResponseError instantiates a new UpdateStockLevel429ResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateStockLevel429ResponseError() *UpdateStockLevel429ResponseError {
	this := UpdateStockLevel429ResponseError{}
	return &this
}

// NewUpdateStockLevel429ResponseErrorWithDefaults instantiates a new UpdateStockLevel429ResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateStockLevel429ResponseErrorWithDefaults() *UpdateStockLevel429ResponseError {
	this := UpdateStockLevel429ResponseError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *UpdateStockLevel429ResponseError) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStockLevel429ResponseError) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *UpdateStockLevel429ResponseError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *UpdateStockLevel429ResponseError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UpdateStockLevel429ResponseError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStockLevel429ResponseError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UpdateStockLevel429ResponseError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UpdateStockLevel429ResponseError) SetMessage(v string) {
	o.Message = &v
}

func (o UpdateStockLevel429ResponseError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateStockLevel429ResponseError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableUpdateStockLevel429ResponseError struct {
	value *UpdateStockLevel429ResponseError
	isSet bool
}

func (v NullableUpdateStockLevel429ResponseError) Get() *UpdateStockLevel429ResponseError {
	return v.value
}

func (v *NullableUpdateStockLevel429ResponseError) Set(val *UpdateStockLevel429ResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateStockLevel429ResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateStockLevel429ResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateStockLevel429ResponseError(val *UpdateStockLevel429ResponseError) *NullableUpdateStockLevel429ResponseError {
	return &NullableUpdateStockLevel429ResponseError{value: val, isSet: true}
}

func (v NullableUpdateStockLevel429ResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateStockLevel429ResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


