/*
Integration Adapter

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the AccountsRequestAccountsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountsRequestAccountsInner{}

// AccountsRequestAccountsInner struct for AccountsRequestAccountsInner
type AccountsRequestAccountsInner struct {
	Data *string `json:"data,omitempty"`
}

// NewAccountsRequestAccountsInner instantiates a new AccountsRequestAccountsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountsRequestAccountsInner() *AccountsRequestAccountsInner {
	this := AccountsRequestAccountsInner{}
	return &this
}

// NewAccountsRequestAccountsInnerWithDefaults instantiates a new AccountsRequestAccountsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountsRequestAccountsInnerWithDefaults() *AccountsRequestAccountsInner {
	this := AccountsRequestAccountsInner{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AccountsRequestAccountsInner) GetData() string {
	if o == nil || IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountsRequestAccountsInner) GetDataOk() (*string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AccountsRequestAccountsInner) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *AccountsRequestAccountsInner) SetData(v string) {
	o.Data = &v
}

func (o AccountsRequestAccountsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountsRequestAccountsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableAccountsRequestAccountsInner struct {
	value *AccountsRequestAccountsInner
	isSet bool
}

func (v NullableAccountsRequestAccountsInner) Get() *AccountsRequestAccountsInner {
	return v.value
}

func (v *NullableAccountsRequestAccountsInner) Set(val *AccountsRequestAccountsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountsRequestAccountsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountsRequestAccountsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountsRequestAccountsInner(val *AccountsRequestAccountsInner) *NullableAccountsRequestAccountsInner {
	return &NullableAccountsRequestAccountsInner{value: val, isSet: true}
}

func (v NullableAccountsRequestAccountsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountsRequestAccountsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


